<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
    <head>
      <meta http-equiv="content-type" content="text/html; charset=utf-8" />
      <title>HaskWOOL Debugger</title>
      <link rel="stylesheet" href="/static/tutorial.css" type="text/css" />
    </head>

    <body>
	$ headerarea $
	    <div id="content"> 
	      <table> <tr> <td valign=top width = 50> $ tocarea $ </td> 
		      <td valign=top> $ contentarea $ </td>
                      <td width=100></td>
	      </tr> </table>
	    </div> 

	$ googleanalytics() $

	$ footer() $

    </body>
</html>
