<table><tr>
     <td> 
           $ menubarMenu $
     </td>
     <td width=50> $! td is for alignment only, an ugly hack, and it renders bad if you resize the window.
                       how can I do this better? !$ </td> 
     <td align=right> $ userMenu $ </td>
</tr>
<tr> <td colsize=3> $mainUserMenu$ </td> $! colsize is wrong, google on correct attribute!$
</tr>
</table>






           




