
<?php

// PHP file to save haskell code passed and execute it

// runghc location
$ghc = "/home/dmundra/ghc/live/bin/ghc";
$runghc = "/home/dmundra/ghc/live/bin/runghc";

// Filename and code passed when debug.php is called
$fname = $_POST["fname"];
$module = $_POST["module"];
$code = $_POST["code"];
$pid = "";

$mainFName = substr($fname,0,-3);

$code = str_replace("\\","",$code); // For unix only replace slashes that were generated by the code

$main = "module Main where
import System.Environment
import WOOL
import WOOLUtil
import WOOLIO
import WOOLPrimitives
import WOOLServer
import qualified ". $mainFName ." as WF

main = do
    args <- getArgs -- getArgs is from System.Environment, if you're not familiar with it
    runWOOLServer args WF." . strtolower($mainFName) . "workflow";

if($code != "")	{

	$checkdir = chdir("hwserver/src");

	if($checkdir == "true") {
		// Create hs file with code
		$fp = fopen('' . $fname, 'w+');
		fwrite($fp, $code);
		fclose($fp);

		// Create Main file with code
		$fp = fopen('Main.hs', 'w+');
		fwrite($fp, $main);
		fclose($fp);

		// If the file is a module it will have no main so it will not be executed, it will be only saved as a file
		if($module == "false") {
			echo "<pre>Creating HaskWool Server Instance...(click 'try again' a couple of times)</pre>";

			$checkdir = chdir("../");

			$port = 5001;

			$dummy = exec('nohup '. $runghc .' -isrc/ -i../ src/Main.hs '. $port .' True False > haskwool.log 2>&1 & echo $!', $output);
			$dummy = sleep(2);

			echo "<pre>The process is currently running: \n";

			$pid = $output[0];

			echo "</pre>";
			$dummy = sleep(2);
			echo "<iframe src='http://cca.d.cs.uoregon.edu:".$port."/' width='750px' height='580px'></iframe>";

		} else {
			echo "<pre>Module saved!</pre>";
		}
	} else {
		echo "<pre>" . getcwd() . " directory doesn't exist</pre>";
	}
} else {
	echo "<pre>No workflow selected! </pre>";
}

?>

<form method="post" action="process.php">
	<input style="display:none;" type="text" name="op" value="<?php echo $pid; ?>"/>
	<input type="submit" name="Submit" value="Kill" />
</form>